### ISSUE TITLE
Update access to Google maps

### ISSUE THREAD

**Issue by deb761** [MobileApps-Cascadia/hidenseek-phase3#22]
The API reference to Google maps is out of date.  Update the code to use the current Google Maps API.

## DoD
When the match starts:
1.  The Hider is shown the google map with the map zoomed in on an appropriate location
2. The map shows the location of the hider

**Comment by Bansenauer-Cascadia** [comment]
Reference from the last students working on this project they thought would come in handy.

https://developers.google.com/maps/documentation/geocoding/
https://developers.google.com/maps/documentation/geocoding/intro
The "Explore CA" app <--  in the google play store
