### ISSUE TITLE
Create and Host a Match

### ISSUE THREAD

**Issue by deb761** [MobileApps-Cascadia/hidenseek-phase3#4]
Implement part of the Use Case for the Seeker:

1 Select Host a Match
2 Define the match
3 See list of players with button to start match
![wireframes_0001](https://cloud.githubusercontent.com/assets/9601218/19749522/7de2c10c-9b9e-11e6-8ff2-712de8df9f45.jpg)

View the data at http://216.186.69.45/services/hidenseek/

**Comment by Cascadia-DebraWard** [comment]
DoD: When a player taps the "Host Match" button they are able to create a match that others can join.

**Comment by Bansenauer-Cascadia** [comment]
Verified complete
