### ISSUE TITLE
Show Seeker list of Hiders

### ISSUE THREAD

**Issue by deb761** [MobileApps-Cascadia/hidenseek-phase3#7]
Show a list of hiders with the distance from the Seeker for each given as a range of Cold - Hot.
- Hot/Cold could be Hot = moving closer, Cold = moving away
- or Hot <=  Distance_Close and Cold > Distance_Far

![wireframes_0001](https://cloud.githubusercontent.com/assets/9601218/19750240/77951632-9ba4-11e6-9d00-ccad54e7a179.jpg)

![image](https://cloud.githubusercontent.com/assets/11932312/20901262/904f6bee-bae6-11e6-976d-b4ea3d5ba00c.png)

**Comment by Benmoony** [comment]
DoD: On the list of players for the seeker, provide a symbol indicating whether or not the seeker is close to or far away from the player for each player in the list.
